svn add       toadd.sh
svn add       autogen.sh
svn add       ChangeLog
svn add       m4/ax_check_compiler_flags.m4
svn add       m4/acx_pthread.m4
svn add       gtk/hslicecontrols.glade
svn add       gtk/gtkrc
svn add       gtk/dummy.C
svn add       gtk/colorselectiondialog.c
svn add       src/graphics.pex.c
svn add       src/igrid.c
svn add       src/pi.c
svn add       src/oldrecord.c
svn add       src/memory_i.c
svn add       src/newproj.c
svn add       src/memory_i.h
svn add       src/cb.c
svn add       src/own.c
svn add       src/p
svn add       src/vertplot.c
svn add       src/irregular_api.c
svn add       src/fsl.c
svn add       src/ifdefs.out
svn add       src/graphics.gl.c
svn add       lui5/help.c
svn add       lui5/Makefile.am
svn add       lui5/dialog.c
svn add       lui5/popup.c
svn add       lui5/browser2.h

