svn --force del config.h.in
svn --force del autom4te.cache
svn --force del missing
svn --force del util/Makefile.in
svn --force del util/igg3d
svn --force del util/igu3d
svn --force del util/gr3d_to_v5d
svn --force del util/gg3d
svn --force del aclocal.m4
svn --force del install-sh
svn --force del m4/lt~obsolete.m4
svn --force del m4/ltoptions.m4
svn --force del m4/ltsugar.m4
svn --force del m4/libtool.m4
svn --force del m4/ltversion.m4
svn --force del m4/codeset.m4
svn --force del m4/progtest.m4
svn --force del m4/iconv.m4
svn --force del m4/lib-link.m4
svn --force del m4/lib-prefix.m4
svn --force del m4/Makefile.in
svn --force del m4/glibc21.m4
svn --force del m4/lcmessage.m4
svn --force del m4/lib-ld.m4
svn --force del m4/gettext.m4
svn --force del configure
svn --force del Makefile.in
svn --force del config.rpath
svn --force del gtk/.deps
svn --force del gtk/gradients/.deps
svn --force del gtk/gradients/Makefile
svn --force del gtk/gradients/Makefile.in
svn --force del gtk/vis5dgtk.pc
svn --force del gtk/Makefile
svn --force del gtk/Makefile.in
svn --force del src/Makefile.in
svn --force del src/api-config.h
svn --force del src/stamp-h2
svn --force del depcomp
svn --force del config.guess
svn --force del config.sub
svn --force del ltmain.sh
svn --force del ABOUT-NLS
svn --force del doc/Makefile.in
svn --force del INSTALL
svn --force del "po/en@quot.header@"
svn --force del po/quot.sed
svn --force del po/boldquot.sed
svn --force del "po/en@boldquot.header@"
svn --force del po/Makevars
svn --force del po/Rules-quot
svn --force del po/insert-header.sin
svn --force del po/POTFILES
svn --force del po/remove-potcdate.sin
svn --force del po/Makefile.in.in
svn --force del lui5/Makefile.in
svn --force del mkinstalldirs
svn --force del ChangeLog
svn --force del stamp-h1
svn --force del make.log
