svn --force del      m4/Makefile
svn --force del      config.log
svn --force del      gtk/Makefile
svn --force del      gtk/gradients/Makefile
svn --force del      gtk/vis5dgtk.pc
svn --force del      src/v5dimport
svn --force del      src/.deps/sounding.Plo
svn --force del      src/.deps/labels.Po
svn --force del      src/.deps/read_grid_i.Plo
svn --force del      src/.deps/tclsave.Plo
svn --force del      src/.deps/cursor.Po
svn --force del      src/.deps/read_gr3d_i.Plo
svn --force del      src/.deps/sgidump.Plo
svn --force del      src/.deps/api.Plo
svn --force del      src/.deps/isocolor.Po
svn --force del      src/.deps/graphics.ogl.Plo
svn --force del      src/.deps/main_i.Po
svn --force del      src/.deps/resample_i.Plo
svn --force del      src/.deps/topo.Plo
svn --force del      src/.deps/igui.Po
svn --force del      src/.deps/pipe.Po
svn --force del      src/.deps/proj_i.Plo
svn --force del      src/.deps/image.Plo
svn --force del      src/.deps/slice.Po
svn --force del      src/.deps/contour.Plo
svn --force del      src/.deps/stream.Plo
svn --force del      src/.deps/displaywidget.Po
svn --force del      src/.deps/grid_i.Plo
svn --force del      src/.deps/xdump.Plo
svn --force del      src/.deps/binio.Plo
svn --force del      src/.deps/read_v5d_i.Plo
svn --force del      src/.deps/graphics.all.Plo
svn --force del      src/.deps/user_data.Plo
svn --force del      src/.deps/memory.Plo
svn --force del      src/.deps/main.Po
svn --force del      src/.deps/read_epa_i.Plo
svn --force del      src/.deps/output_i.Plo
svn --force del      src/.deps/pngdump.Plo
svn --force del      src/.deps/proj.Plo
svn --force del      src/.deps/rgb.Plo
svn --force del      src/.deps/analyze_i.Plo
svn --force del      src/.deps/linterp.Plo
svn --force del      src/.deps/map.Plo
svn --force del      src/.deps/soundingGUI.Po
svn --force del      src/.deps/graphics.vrml.Plo
svn --force del      src/.deps/graphics.scenes.Plo
svn --force del      src/.deps/file.Plo
svn --force del      src/.deps/render.Plo
svn --force del      src/.deps/socketio.Plo
svn --force del      src/.deps/gl_to_ppm.Plo
svn --force del      src/.deps/textplot.Plo
svn --force del      src/.deps/analysis.Plo
svn --force del      src/.deps/globals.Plo
svn --force del      src/.deps/anim.Plo
svn --force del      src/.deps/rgbsliders.Po
svn --force del      src/.deps/box.Plo
svn --force del      src/.deps/chrono.Plo
svn --force del      src/.deps/script.Po
svn --force del      src/.deps/vtmcP.Plo
svn --force del      src/.deps/misc.Plo
svn --force del      src/.deps/v5d.Plo
svn --force del      src/.deps/tokenize_i.Plo
svn --force del      src/.deps/read_grads_i.Plo
svn --force del      src/.deps/groupchrono.Plo
svn --force del      src/.deps/volume.Plo
svn --force del      src/.deps/uvwwidget.Po
svn --force del      src/.deps/ui_i.Po
svn --force del      src/.deps/v5dimport.Po
svn --force del      src/.deps/gui_i.Po
svn --force del      src/.deps/imemory.Plo
svn --force del      src/.deps/iapi.Plo
svn --force del      src/.deps/file_i.Plo
svn --force del      src/.deps/save.Plo
svn --force del      src/.deps/mwmborder.Plo
svn --force del      src/.deps/traj.Plo
svn --force del      src/.deps/misc_i.Plo
svn --force del      src/.deps/matrix.Plo
svn --force del      src/.deps/gui.Po
svn --force del      src/.deps/irregular_v5d.Plo
svn --force del      src/.deps/compute.Plo
svn --force del      src/.deps/sync.Plo
svn --force del      src/.deps/record.Plo
svn --force del      src/.deps/projlist_i.Plo
svn --force del      src/.deps/read_uwvis_i.Plo
svn --force del      src/.deps/imain.Po
svn --force del      src/.deps/work.Plo
svn --force del      src/.deps/queue.Plo
svn --force del      src/.deps/grid.Plo
svn --force del      src/Makefile
svn --force del      src/vis5d
svn --force del      src/libvis5dgui.a
svn --force del      src/.libs/libvis5d.a
svn --force del      src/.libs/libv5d.so.2.0.0
svn --force del      src/.libs/libv5d.a
svn --force del      src/.libs/libvis5d.lai
svn --force del      src/.libs/libv5d.lai
svn --force del      src/.libs/v5dimport
svn --force del      src/.libs/vis5d
svn --force del      src/.libs/libvis5d.so.2.0.0
svn --force del      config.h
svn --force del      jonconfigure.sh
svn --force del      doc/Makefile
svn --force del      Makefile
svn --force del      lui5/.deps/colorbar.Po
svn --force del      lui5/.deps/browser2.Po
svn --force del      lui5/.deps/button.Po
svn --force del      lui5/.deps/list.Po
svn --force del      lui5/.deps/label.Po
svn --force del      lui5/.deps/pixmaps.Po
svn --force del      lui5/.deps/event.Po
svn --force del      lui5/.deps/scrollbar.Po
svn --force del      lui5/.deps/browser.Po
svn --force del      lui5/.deps/field.Po
svn --force del      lui5/.deps/newbutton.Po
svn --force del      lui5/.deps/newlist.Po
svn --force del      lui5/.deps/destroy.Po
svn --force del      lui5/.deps/lui.Po
svn --force del      lui5/.deps/newlabel.Po
svn --force del      lui5/.deps/newslider.Po
svn --force del      lui5/.deps/newbrowser.Po
svn --force del      lui5/.deps/radio.Po
svn --force del      lui5/.deps/buttonmatrix.Po
svn --force del      lui5/Makefile
svn --force del      lui5/liblui.a
svn --force del      po/Makefile.in
svn --force del      po/pt_BR.po
svn --force del      po/pt_BR.gmo
svn --force del      po/Makefile
svn --force del      config.status
svn --force del      libtool
svn --force del      vis5d+.pc
svn --force del      util/v5dappend
!       util/igg3d
svn --force del      util/topoinfo
svn --force del      util/v5dedit
svn --force del      util/.libs/maketopo
svn --force del      util/.libs/v5dedit
svn --force del      util/.libs/v5dappend
svn --force del      util/.libs/v5dinfo
svn --force del      util/.libs/makemap
svn --force del      util/.libs/topoinfo
svn --force del      util/.libs/v5dstats
svn --force del      util/.libs/comp_to_v5d
svn --force del      util/.deps/main.Po
svn --force del      util/.deps/v5dedit.Po
svn --force del      util/.deps/v5dappend.Po
svn --force del      util/.deps/v5dinfo.Po
svn --force del      util/.deps/makemap.Po
svn --force del      util/.deps/topoinfo.Po
svn --force del      util/.deps/v5dstats.Po
svn --force del      util/.deps/comp_to_v5d.Po
svn --force del      util/.deps/maketopo.Po
svn --force del      util/Makefile
svn --force del      util/maketopo
svn --force del      util/v5dinfo
svn --force del      util/makemap
svn --force del      util/v5dstats
svn --force del      util/comp_to_v5d
